install:
  - set QTDIR=C:\Qt\5.15.1\mingw81_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - set BIN=DL-JS
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\Qt\5.15.1\mingw81_64\qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER% DL-JS_Lis.pro
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin\mingw32-make

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - dir /b /s *.exe
  - mkdir deploy
  - dir /s %APPVEYOR_BUILD_FOLDER%-build
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\%BIN%.exe deploy\%BIN%.exe
  - windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%/qml --%CONFIGURATION% deploy/%BIN%.exe --verbose=2
  - for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I deploy\
  - 7z a -mtr=off -mtm=off -mta=off -mtc=off -mhc=on -mf=on -ms=on -mqs=on -mmf=bt4 -mfb=273 -mmc=1000000000 -md=1536M -mx=9 -myx=9 -ma=1 %BIN%_%CONFIGURATION%.7z deploy -r
  - copy %APPVEYOR_BUILD_FOLDER%-build\%BIN%_%CONFIGURATION%.7z %APPVEYOR_BUILD_FOLDER%\%BIN%_%CONFIGURATION%.7z
  - dir /b /s *.7z

artifacts:
  - path: '%BIN%_%CONFIGURATION%.7z'
    name: '%BIN%'
