version: '{branch}-{build}'

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )

# os: Visual Studio 2019

environment:
  matrix:
    - job_name: VisualStudio19
      MSVC_VERSION: 19
      RUNTIME_LINKAGE: static
      QT_VERSION: 5.15
      QT_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      #https://www.appveyor.com/docs/build-environment/#qt
      QTDIR: C:\Qt\%QT_VERSION%\msvc2019_64
      PRJLIBS: VCRUNTIME140.dll MSVCP140.dll ucrtbased.dll

    - job_name: MinGwin64
      RUNTIME_LINKAGE: static
      QT_VERSION: 5.15
      QT_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      #https://www.appveyor.com/docs/build-environment/#qt
      QTDIR: C:\Qt\%QT_VERSION%\mingw81_64
      PRJLIBS: libgcc_s_seh-1.dll libstdc++-6.dll libwinpthread-1.dll
configuration:
  - release
  - debug

install:
  # Set and load necessary variables
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - set PRJLIBDIR=%WINDIR%\SysWOW64 # Find vclibss
  - set QTDIR
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - set BIN=DL-JS_Lis

before_build:
  # Prepare the out-of-source build directory.
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  # Compile it and check for .exe
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - nmake
  - dir /b /s *.exe

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - echo "Agregando youtube-dl"
  - $source = "https://youtube-dl.org/downloads/latest/youtube-dl.exe"
  - $destination = "%APPVEYOR_BUILD_FOLDER%\youtube-dl.exe"
  - Invoke-WebRequest $source -OutFile $destination
  - dir /b /s *.exe
  - mkdir deploy
  - copy %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\%BIN%.exe deploy\%BIN%.exe
  - windeployqt --qmldir %APPVEYOR_BUILD_FOLDER%/qml --%CONFIGURATION% deploy/%BIN%.exe --verbose=2
  - for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I deploy\
  - 7z a x=9 yx=9 tr=off tm=off  mf=bt4 fb=273 mc=1000000000 d=1536M %BIN%_%CONFIGURATION%.7z deploy -r
  - copy %APPVEYOR_BUILD_FOLDER%-build\%BIN%_%CONFIGURATION%.7z %APPVEYOR_BUILD_FOLDER%\%BIN%_%CONFIGURATION%.7z
  - dir /b /s *.zip

artifacts:
  - path: '%BIN%_%CONFIGURATION%.zip'
    name: '%BIN%'

deploy:
  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
  description: 'Auto Build'
  provider: GitHub
  # auth_token:
    # secure: <your encrypted token> # your encrypted token from GitHub
  artifact: '%BIN%'          # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true 