del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qgif.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qicns.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qico.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qjpeg.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qtga.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qtiff.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qwbmp.dll"
del "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\imageformats\qwebp.dll"
copy /V /Y "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS_Lis\DL-JS.VisualElementsManifest.xml" "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release"
copy /V /Y "C:\Jackestar\Proyectos\CourseCode\QT\Env\ffmpeg.exe" "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release"
md "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\VisualElementsManifest"
copy /V /Y "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS_Lis\VisualElementsManifest" "C:\Jackestar\Proyectos\CourseCode\QT\DL-JS Lis\Win 64 (MinGW)\release\VisualElementsManifest"